clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: true

pipeline:
  build:
    image: node:18-bullseye
    commands:
      - curl https://sh.rustup.rs -sSf | sh -s -- --profile minimal -y
      - . "$HOME/.cargo/env"
      - ./build.sh --public-url matrix-social/
    when:
      event: [ push ]

  publish:
    image: bitnami/git
    # Must be set in Woodpecker configuration
    secrets: [ codeberg_token ]
    commands:
      # Git configuration
      - git config --global user.email "noreply@example.org"
      - git config --global user.name "Woodpecker CI"
      - git clone -b pages https://$CODEBERG_TOKEN@codeberg.org/$CI_REPO.git $CI_REPO_NAME
      # Create a copy of the index for 404 pages
      - cp dist/index.html dist/404.html
      - mv $CI_REPO_NAME/.git ./.git.temp
      - rm -rdf $CI_REPO_NAME
      - mkdir $CI_REPO_NAME
      - mv ./.git.temp $CI_REPO_NAME
      - mv $CI_REPO_NAME/.git.temp $CI_REPO_NAME/.git
      # Copy build step output to repository folder
      - cp -ar dist/. $CI_REPO_NAME/
      # Needed for custom domains
      - cp .domains $CI_REPO_NAME || true # Ignore if it doesn't exist
      # Commit and push all static files with pipeline started timestamp
      - cd $CI_REPO_NAME
      - git add .
      - git commit -m "Woodpecker CI ${CI_BUILD_CREATED}"
      - git push
    when:
      event: push

branches: master